import React from 'react';
import { Box, Typography } from '@mui/material';
import { COLORS, TRANSITIONS } from '../../constants';

interface DealerButtonProps {
  position: {
    left: string;
    top: string;
  };
}

export const DealerButton: React.FC<DealerButtonProps> = ({ position }) => {
  return (
    <Box
      sx={{
        position: 'absolute',
        left: position.left,
        top: position.top,
        transform: 'translate(-50%, -50%)',
        width: 48,
        height: 48,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 25,
        transition: `all ${TRANSITIONS.slow} cubic-bezier(0.4, 0, 0.2, 1)`,

        // Chip outer ring (white)
        background: `linear-gradient(135deg, #ffffff 0%, #e8e8e8 100%)`,
        border: '3px solid #ffffff',
        boxShadow: `
          0 4px 8px rgba(0, 0, 0, 0.3),
          0 2px 4px rgba(0, 0, 0, 0.2),
          inset 0 2px 4px rgba(255, 255, 255, 0.6),
          inset 0 -2px 4px rgba(0, 0, 0, 0.2)
        `,

        '&::before': {
          content: '""',
          position: 'absolute',
          inset: 6,
          borderRadius: '50%',
          background: `linear-gradient(135deg, ${COLORS.danger.main} 0%, #b91c1c 100%)`,
          boxShadow: 'inset 0 2px 4px rgba(0, 0, 0, 0.3)',
        },

        // Chip edge pattern (dashed border simulation)
        '&::after': {
          content: '""',
          position: 'absolute',
          inset: 0,
          borderRadius: '50%',
          background: `conic-gradient(
            from 0deg,
            transparent 0deg,
            transparent 8deg,
            #ffffff 8deg,
            #ffffff 10deg,
            transparent 10deg,
            transparent 18deg,
            #ffffff 18deg,
            #ffffff 20deg,
            transparent 20deg,
            transparent 28deg,
            #ffffff 28deg,
            #ffffff 30deg,
            transparent 30deg,
            transparent 38deg,
            #ffffff 38deg,
            #ffffff 40deg,
            transparent 40deg,
            transparent 48deg,
            #ffffff 48deg,
            #ffffff 50deg,
            transparent 50deg,
            transparent 58deg,
            #ffffff 58deg,
            #ffffff 60deg,
            transparent 60deg,
            transparent 68deg,
            #ffffff 68deg,
            #ffffff 70deg,
            transparent 70deg,
            transparent 78deg,
            #ffffff 78deg,
            #ffffff 80deg,
            transparent 80deg,
            transparent 88deg,
            #ffffff 88deg,
            #ffffff 90deg,
            transparent 90deg,
            transparent 98deg,
            #ffffff 98deg,
            #ffffff 100deg,
            transparent 100deg,
            transparent 108deg,
            #ffffff 108deg,
            #ffffff 110deg,
            transparent 110deg,
            transparent 118deg,
            #ffffff 118deg,
            #ffffff 120deg,
            transparent 120deg,
            transparent 128deg,
            #ffffff 128deg,
            #ffffff 130deg,
            transparent 130deg,
            transparent 138deg,
            #ffffff 138deg,
            #ffffff 140deg,
            transparent 140deg,
            transparent 148deg,
            #ffffff 148deg,
            #ffffff 150deg,
            transparent 150deg,
            transparent 158deg,
            #ffffff 158deg,
            #ffffff 160deg,
            transparent 160deg,
            transparent 168deg,
            #ffffff 168deg,
            #ffffff 170deg,
            transparent 170deg,
            transparent 178deg,
            #ffffff 178deg,
            #ffffff 180deg,
            transparent 180deg,
            transparent 188deg,
            #ffffff 188deg,
            #ffffff 190deg,
            transparent 190deg,
            transparent 198deg,
            #ffffff 198deg,
            #ffffff 200deg,
            transparent 200deg,
            transparent 208deg,
            #ffffff 208deg,
            #ffffff 210deg,
            transparent 210deg,
            transparent 218deg,
            #ffffff 218deg,
            #ffffff 220deg,
            transparent 220deg,
            transparent 228deg,
            #ffffff 228deg,
            #ffffff 230deg,
            transparent 230deg,
            transparent 238deg,
            #ffffff 238deg,
            #ffffff 240deg,
            transparent 240deg,
            transparent 248deg,
            #ffffff 248deg,
            #ffffff 250deg,
            transparent 250deg,
            transparent 258deg,
            #ffffff 258deg,
            #ffffff 260deg,
            transparent 260deg,
            transparent 268deg,
            #ffffff 268deg,
            #ffffff 270deg,
            transparent 270deg,
            transparent 278deg,
            #ffffff 278deg,
            #ffffff 280deg,
            transparent 280deg,
            transparent 288deg,
            #ffffff 288deg,
            #ffffff 290deg,
            transparent 290deg,
            transparent 298deg,
            #ffffff 298deg,
            #ffffff 300deg,
            transparent 300deg,
            transparent 308deg,
            #ffffff 308deg,
            #ffffff 310deg,
            transparent 310deg,
            transparent 318deg,
            #ffffff 318deg,
            #ffffff 320deg,
            transparent 320deg,
            transparent 328deg,
            #ffffff 328deg,
            #ffffff 330deg,
            transparent 330deg,
            transparent 338deg,
            #ffffff 338deg,
            #ffffff 340deg,
            transparent 340deg,
            transparent 348deg,
            #ffffff 348deg,
            #ffffff 350deg,
            transparent 350deg,
            transparent 358deg,
            #ffffff 358deg,
            #ffffff 360deg
          )`,
          mask: 'radial-gradient(circle, transparent 60%, black 60%, black 80%, transparent 80%)',
          WebkitMask: 'radial-gradient(circle, transparent 60%, black 60%, black 80%, transparent 80%)',
        },

        animation: 'dealerPulse 2s ease-in-out infinite',

        '@keyframes dealerPulse': {
          '0%, 100%': {
            transform: 'translate(-50%, -50%) scale(1)',
          },
          '50%': {
            transform: 'translate(-50%, -50%) scale(1.05)',
          },
        },
      }}
    >
      <Typography
        sx={{
          fontSize: '1.25rem',
          fontWeight: 900,
          color: '#ffffff',
          textShadow: '0 2px 4px rgba(0, 0, 0, 0.5)',
          letterSpacing: '0.05em',
          zIndex: 1,
          position: 'relative',
        }}
      >
        D
      </Typography>
    </Box>
  );
};
